
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 11 12:45:27 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 20;
  public static final int DIVIDE = 35;
  public static final int CONST = 3;
  public static final int ASSIGNMENT = 12;
  public static final int RIGHT_SQUARE_BRACKET = 27;
  public static final int NOT_EQUAL = 40;
  public static final int GREATER = 42;
  public static final int SEMI = 8;
  public static final int CONTINUE = 18;
  public static final int LESS = 41;
  public static final int MINUS = 33;
  public static final int AND = 37;
  public static final int RECORD = 49;
  public static final int OR = 38;
  public static final int COMMA = 10;
  public static final int CLASS = 5;
  public static final int INC = 30;
  public static final int LESS_EQUAL = 44;
  public static final int PLUS = 32;
  public static final int MULTIPLY = 34;
  public static final int LEFT_CURLY_BRACKET = 28;
  public static final int IF = 13;
  public static final int THIS = 51;
  public static final int LEFT_ROUND_BRACKET = 24;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int EQUAL = 39;
  public static final int GREATER_EQUAL = 43;
  public static final int SUPER = 50;
  public static final int LEFT_SQUARE_BRACKET = 26;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int NUMBER = 22;
  public static final int BREAK = 17;
  public static final int IDENT = 23;
  public static final int VOID = 4;
  public static final int COLON = 9;
  public static final int ELSE = 14;
  public static final int ENUM = 48;
  public static final int READ = 46;
  public static final int POINT = 11;
  public static final int GOTO = 47;
  public static final int WHILE = 16;
  public static final int EXTENDS = 6;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 21;
  public static final int DEC = 31;
  public static final int MODUO = 36;
  public static final int RIGHT_CURLY_BRACKET = 29;
  public static final int PRINT = 45;
  public static final int DO = 15;
  public static final int RIGHT_ROUND_BRACKET = 25;
}

