
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 09 20:08:51 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 9;
  public static final int DIVIDE = 31;
  public static final int CONST = 3;
  public static final int ASSIGNMENT = 8;
  public static final int RIGHT_SQUARE_BRACKET = 13;
  public static final int NOT_EQUAL = 45;
  public static final int GREATER = 47;
  public static final int CONTINUE = 43;
  public static final int SEMI = 6;
  public static final int LESS = 46;
  public static final int MINUS = 29;
  public static final int AND = 33;
  public static final int RECORD = 38;
  public static final int OR = 34;
  public static final int COMMA = 7;
  public static final int CLASS = 4;
  public static final int INC = 27;
  public static final int LESS_EQUAL = 49;
  public static final int PLUS = 18;
  public static final int MULTIPLY = 30;
  public static final int LEFT_CURLY_BRACKET = 14;
  public static final int IF = 21;
  public static final int THIS = 40;
  public static final int LEFT_ROUND_BRACKET = 50;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int EQUAL = 44;
  public static final int GREATER_EQUAL = 48;
  public static final int SUPER = 39;
  public static final int NEW = 36;
  public static final int LEFT_SQUARE_BRACKET = 12;
  public static final int error = 1;
  public static final int NUMBER = 11;
  public static final int BREAK = 42;
  public static final int IDENT = 20;
  public static final int VOID = 19;
  public static final int COLON = 35;
  public static final int ELSE = 22;
  public static final int POINT = 41;
  public static final int ENUM = 37;
  public static final int READ = 23;
  public static final int GOTO = 24;
  public static final int WHILE = 26;
  public static final int EXTENDS = 5;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 10;
  public static final int DEC = 28;
  public static final int MODUO = 32;
  public static final int RIGHT_CURLY_BRACKET = 15;
  public static final int PRINT = 16;
  public static final int DO = 25;
  public static final int RIGHT_ROUND_BRACKET = 51;
}

