
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 18 12:10:20 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 24;
  public static final int DIVIDE = 39;
  public static final int CONST = 3;
  public static final int ASSIGNMENT = 13;
  public static final int RIGHT_SQUARE_BRACKET = 31;
  public static final int NOT_EQUAL = 44;
  public static final int GREATER = 46;
  public static final int SEMI = 9;
  public static final int CONTINUE = 19;
  public static final int LESS = 45;
  public static final int MINUS = 37;
  public static final int AND = 41;
  public static final int RECORD = 8;
  public static final int OR = 42;
  public static final int COMMA = 11;
  public static final int CLASS = 5;
  public static final int INC = 34;
  public static final int LESS_EQUAL = 48;
  public static final int MULTIPLY = 38;
  public static final int PLUS = 36;
  public static final int LEFT_CURLY_BRACKET = 32;
  public static final int IF = 14;
  public static final int LEFT_ROUND_BRACKET = 28;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int EQUAL = 43;
  public static final int GREATER_EQUAL = 47;
  public static final int LEFT_SQUARE_BRACKET = 30;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int NUMBER = 26;
  public static final int BREAK = 18;
  public static final int IDENT = 27;
  public static final int VOID = 4;
  public static final int COLON = 10;
  public static final int ELSE = 15;
  public static final int ENUM = 49;
  public static final int POINT = 12;
  public static final int READ = 23;
  public static final int GOTO = 21;
  public static final int WHILE = 17;
  public static final int EXTENDS = 6;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 25;
  public static final int DEC = 35;
  public static final int MODUO = 40;
  public static final int RIGHT_CURLY_BRACKET = 33;
  public static final int PRINT = 22;
  public static final int DO = 16;
  public static final int RIGHT_ROUND_BRACKET = 29;
}

